/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About/About.vue')['default']
    AuthFrame: typeof import('./src/components/Auth/AuthFrame.vue')['default']
    Banner: typeof import('./src/components/Banner/Banner.vue')['default']
    Basic: typeof import('./src/components/Chart/Basic/index.vue')['default']
    Blog: typeof import('./src/components/Cards/Blog.vue')['default']
    Category: typeof import('./src/components/Cards/Category.vue')['default']
    Contact: typeof import('./src/components/Auth/Contact.vue')['default']
    Cross: typeof import('./src/components/Parallax/Cross.vue')['default']
    Dot: typeof import('./src/components/Parallax/Dot.vue')['default']
    Explore: typeof import('./src/components/Explore/Explore.vue')['default']
    Feature: typeof import('./src/components/Feature/Feature.vue')['default']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    ForgotPassword: typeof import('./src/components/Auth/ForgotPassword.vue')['default']
    FormConfirmDelete: typeof import('./src/components/Form/FormConfirmDelete.vue')['default']
    FormContainer: typeof import('./src/components/Form/FormContainer.vue')['default']
    FormDialog: typeof import('./src/components/Form/FormDialog.vue')['default']
    FormFullPage: typeof import('./src/components/Form/FormFullPage.vue')['default']
    FormGeneral: typeof import('./src/components/Form/FormGeneral.vue')['default']
    FormHelper: typeof import('./src/components/Form/FormHelper.vue')['default']
    FormTable: typeof import('./src/components/Form/FormTable.vue')['default']
    General: typeof import('./src/components/Cards/General.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hidden: typeof import('./src/components/Hidden/index.vue')['default']
    Index: typeof import('./src/components/Chart/Pie/Index.vue')['default']
    Login: typeof import('./src/components/Auth/Login.vue')['default']
    MobileMenu: typeof import('./src/components/Header/MobileMenu.vue')['default']
    PageNav: typeof import('./src/components/PageNav/PageNav.vue')['default']
    PopularCourse: typeof import('./src/components/PopularCourse/PopularCourse.vue')['default']
    Register: typeof import('./src/components/Auth/Register.vue')['default']
    RegSuccess: typeof import('./src/components/Auth/RegSuccess.vue')['default']
    ResetSuccess: typeof import('./src/components/Auth/ResetSuccess.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Header/Settings.vue')['default']
    SImpleCard: typeof import('./src/components/Card/SImpleCard.vue')['default']
    SocialAuth: typeof import('./src/components/Auth/SocialAuth.vue')['default']
    Testimonial: typeof import('./src/components/Cards/Testimonial.vue')['default']
    Title: typeof import('./src/components/Title/Title.vue')['default']
    Uploader: typeof import('./src/components/Uploader/index.vue')['default']
  }
}
